services:
  - type: worker
    name: creatormind-workers
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm run worker
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        generateValue: false
      - key: UPSTASH_REDIS_REST_URL
        generateValue: false
      - key: UPSTASH_REDIS_REST_TOKEN
        generateValue: false
      - key: UPSTASH_REDIS_URL
        generateValue: false
      - key: YOUTUBE_API_KEY
        generateValue: false
      - key: GEMINI_API_KEY
        generateValue: false
      - key: GOOGLE_CLIENT_ID
        generateValue: false
      - key: GOOGLE_CLIENT_SECRET
        generateValue: false
      - key: MAILJET_API_KEY
        generateValue: false
      - key: MAILJET_SECRET_KEY
        generateValue: false
      - key: MAILJET_SENDER_EMAIL
        generateValue: false
      - key: NEXT_PUBLIC_APP_URL
        generateValue: false
